interseg:
  inpath: ../images/patient_tissue2\README.txt
  FISH_color: red
meta_overlay:
  inpath: du145_red_hsr
  color_sensitivity: 85
metaseg:
  inpath: du145_red_hsr
nuclei_fish:
  inpath: ../im2

  # Peak Threshold Parameters
  normal_threshold: 15
  intensity_threshold_std_coeff: 1
  min_cc_size: 9

  # Gaussian Kernel Parameters
  gaussian_kernel_shape: [7, 7]
  gaussian_sigma: 3

  # Cosmetic Parameters
  line_thickness: 2

  # NuSeT Parameters
  min_score: 0.95
  nms_threshold: 0.01
  nuclei_size_T: 500
  scale_ratio: 0.3
