interseg:
  inpath: ./example_interSeg
  FISH_color: green
  has_centromeric_probe: False
stat_fish:
  inpath: ./example_interSeg
  scale: 1
  use_min_cut: True
  nuclei_size_T: 5000
meta_overlay:
  inpath: ../images
  color_sensitivity: 85
metaseg:
  inpath: ../images
fish_distance_calculation:
  inpath: ./example_interSeg
  centromere_probe_color: green
  fish_probe_color: red
  max_centromeric_spots: 3
