interseg:
  FISH_color: green
  inpath: /home/giprasad/Siavash_ecSeg_Analysis/scratch/THP1_gCEP1_rMycL1_interphase
meta_overlay:
  color_sensitivity: 85
  inpath: du145_red_hsr
metaseg:
  inpath: /home/giprasad/Siavash_ecSeg_Analysis/scratch/SNU16_gCEP10_rFGFR2
nuclei_fish:
  gaussian_kernel_shape:
  - 7
  - 7
  gaussian_sigma: 3
  inpath: /home/giprasad/Siavash_ecSeg_Analysis/scratch/354PDX
  intensity_threshold_std_coeff: 1
  line_thickness: 2
  min_cc_size: 9
  min_nuclei_size: 1000
  min_score: 0.95
  nms_threshold: 0.01
  normal_threshold: 15
  nuclei_size_T: 500
  scale_ratio: 0.3
  target_median_nuclei_size: 2000
