interseg:
  FISH_color: red
  inpath: /home/giprasad/Anton_ecDNA_Analysis/scratch/preprocessed_ecseg-i-distributed_8_red/group_6
meta_overlay:
  color_sensitivity: 85
  inpath: du145_red_hsr
metaseg:
  inpath: du145_red_hsr
nuclei_fish:
  gaussian_kernel_shape:
  - 7
  - 7
  gaussian_sigma: 3
  inpath: /home/giprasad/test_dataset_3_channel
  intensity_threshold_std_coeff: 1
  line_thickness: 2
  min_cc_size: 9
  min_score: 0.95
  nms_threshold: 0.01
  normal_threshold: 15
  nuclei_size_T: 500
  scale_ratio: 0.3
