metaseg:
        inpath :  "images"

meta_overlay:
        inpath :  "snu16"
        FISH_color : "red"
        two_fish_bool : "True"
        color_sensitivity : 85

nuclei_fish:
        inpath :  "images"
        FISH_color : "red"
        color_sensitivity : 85
