interseg:
  inpath: /home/giprasad/Siavash_ecSeg_Analysis/scratch/THP1_gCEP1_rMycL1_interphase
  FISH_color: green
meta_overlay:
  inpath: du145_red_hsr
  color_sensitivity: 85
metaseg:
  inpath: /home/giprasad/Siavash_ecSeg_Analysis/scratch/SNU16_gCEP10_rFGFR2
nuclei_fish:
  inpath: /home/giprasad/Siavash_ecSeg_Analysis/scratch/HCC827_gCON7_rEGFR_interphase

  # Peak Threshold Parameters
  normal_threshold: 15
  intensity_threshold_std_coeff: 1
  min_cc_size: 9
  
  # Image Resizing Parameters
  min_nuclei_size: 1000
  target_median_nuclei_size: 2000

  # Gaussian Kernel Parameters
  gaussian_kernel_shape: [7, 7]
  gaussian_sigma: 3

  # Cosmetic Parameters
  line_thickness: 2

  # NuSeT Parameters
  min_score: 0.95
  nms_threshold: 0.01
  nuclei_size_T: 500
  scale_ratio: 0.3
