interseg:
  inpath: ../images
  FISH_color: red
  has_centromeric_probe: True
meta_overlay:
  inpath: ../images
  color_sensitivity: 85
metaseg:
  inpath: ../images
stat_fish:
  inpath: ../images
  scale: 1
  use_min_cut: True
  nuclei_size_T: 500
fish_distance_calculation:
  inpath: ../images
  centromere_probe_color: green
  fish_probe_color: red
  max_centromeric_spots: 3
