metaseg:
        inpath :  "images"

meta_overlay:
        inpath :  "images/"
        FISH_color : "green"
        color_sensitivity : 70

interseg:
        inpath : "./../Interphase2/ecDNA/green"
        FISH_color : 'green'