interseg:
  FISH_color: green
  inpath: HER2\
meta_overlay:
  color_sensitivity: 85
  inpath: du145_red_hsr
metaseg:
  inpath: du145_red_hsr
nuclei_fish:
  color_sensitivity: 85
  nuclei_size_T: 500
  inpath: du145_red_hsr
  min_score: 0.95
  nms_threshold: 0.01
  scale_ratio: 0.1
