metaseg:
        inpath :  "images"

meta_overlay:
        inpath :  "snu16"
        FISH_color : "red"
        two_fish_bool : "True"
        color_sensitivity : 85

nuclei_fish:
        inpath :  "tif"
        FISH_color : "red"
        color_sensitivity : 85
        min_score : 0.95
        nms_threshold : 0.15
        scale_ratio : 1.0
